# Generated by Django 3.0.2 on 2020-01-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
