# Generated by Django 3.0.2 on 2020-01-28 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='description',
        ),
    ]
