# Generated by Django 3.0.2 on 2020-01-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks_app', '0004_auto_20200128_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spirit', models.CharField(max_length=100)),
                ('recipe', models.TextField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
