# Generated by Django 3.0.2 on 2020-01-28 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks_app', '0005_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='spirit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='drinks_app.Drink'),
        ),
    ]
